version: '3.8'

services:
  pg:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

  polling-bee:
    container_name: polling-bee
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      # Database configuration
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/getPolls/system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - pg
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
